language: python
python:
  - "3.6"

cache: pip

install:
  - pip install pipenv
  - pipenv install --dev

before_script:
  # download the dataset before running the tests
  - python -m download.download_dataset

script:
  - pytest --flake8 -v
